import { Platform, StyleSheet } from 'react-native';

export function makeStyles(c) {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'flex-start',
      paddingTop: Platform.OS === 'ios' ? 60 : 38,
      paddingBottom: 24,
    },
    topBar: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      width: '90%',
      gap: 6,
      marginBottom: 2,
    },
    topBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.chipBg,
      borderWidth: 1,
      borderColor: c.chipBorder,
    },
    topBtnIcon: { color: c.gold, fontSize: 18 },

    header: { alignItems: 'center', marginBottom: 12, width: '90%' },
    eyebrow: { color: c.gold, letterSpacing: 3, fontSize: 11, marginBottom: 8 },
    tirthCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 30,
      paddingVertical: 8,
      paddingHorizontal: 22,
      maxWidth: '100%',
    },
    tirthName: { color: c.text, fontSize: 21, fontWeight: '700', letterSpacing: 0.5 },
    tirthCardChevron: { color: c.gold, fontSize: 14, marginLeft: 8, marginTop: 2 },
    placeLine: { color: c.goldBright, fontSize: 13, fontWeight: '600', marginTop: 6 },
    coords: { color: c.textMuted, fontSize: 12, marginTop: 8 },

    dialWrap: { alignItems: 'center', justifyContent: 'center', marginVertical: 6 },
    glowRing: { position: 'absolute', borderWidth: 1 },
    topNotch: {
      position: 'absolute',
      top: -8,
      width: 0,
      height: 0,
      borderLeftWidth: 8,
      borderRightWidth: 8,
      borderTopWidth: 14,
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
      borderTopColor: c.goldBright,
    },
    needleWrap: { position: 'absolute' },
    centerHub: {
      position: 'absolute',
      width: 92,
      height: 92,
      borderRadius: 46,
      backgroundColor: c.hubBg,
      borderWidth: 2,
      borderColor: c.gold,
      alignItems: 'center',
      justifyContent: 'center',
    },
    headingDeg: { color: c.goldBright, fontSize: 30, fontWeight: '700', lineHeight: 34 },
    headingCard: { color: c.textMuted, fontSize: 13, letterSpacing: 1, marginTop: 2 },

    statusPill: {
      marginTop: 16,
      paddingVertical: 9,
      paddingHorizontal: 20,
      borderRadius: 22,
      backgroundColor: c.pillBg,
      borderWidth: 1,
      borderColor: c.pillBorder,
    },
    statusPillOn: { backgroundColor: c.pillOnBg, borderColor: c.pillOnBorder },
    statusText: { color: c.text, fontSize: 15, fontWeight: '600' },

    infoCard: {
      marginTop: 16,
      width: '86%',
      backgroundColor: c.cardBg,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: c.cardBorder,
      paddingVertical: 6,
      paddingHorizontal: 20,
    },
    infoRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
    },
    divider: { height: 1, backgroundColor: c.divider },
    infoLabel: { color: c.textMuted, fontSize: 14 },
    infoValue: { color: c.text, fontSize: 16, fontWeight: '600' },
    errorText: { color: '#e08a8a', textAlign: 'center', paddingVertical: 14 },
    footerNote: { color: c.footer, fontSize: 11, marginTop: 14, textAlign: 'center', width: '80%' },

    // Modals
    modalBackdrop: { flex: 1, backgroundColor: c.overlay, justifyContent: 'flex-end' },
    modalSheet: {
      backgroundColor: c.sheetBg,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      borderWidth: 1,
      borderColor: c.cardBorder,
      paddingHorizontal: 18,
      paddingTop: 10,
      paddingBottom: 28,
      maxHeight: '82%',
    },
    modalHandle: {
      alignSelf: 'center',
      width: 42,
      height: 5,
      borderRadius: 3,
      backgroundColor: c.cardBorder,
      marginBottom: 10,
    },
    modalHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    modalTitle: { color: c.text, fontSize: 20, fontWeight: '700' },
    modalCloseBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.chipBg,
      borderWidth: 1,
      borderColor: c.chipBorder,
    },
    modalClose: { color: c.gold, fontSize: 16, fontWeight: '700' },

    // Settings
    settingLabel: {
      color: c.textMuted,
      fontSize: 13,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginTop: 8,
      marginBottom: 10,
    },
    segment: {
      flexDirection: 'row',
      backgroundColor: c.chipBg,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.chipBorder,
      padding: 4,
      marginBottom: 18,
      gap: 4,
    },
    segmentBtn: {
      flex: 1,
      paddingVertical: 12,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    segmentBtnOn: { backgroundColor: c.gold },
    segmentText: { color: c.textMuted, fontSize: 15, fontWeight: '600' },
    segmentTextOn: { color: c.chipTextOn },
    doneBtn: {
      marginTop: 6,
      backgroundColor: c.gold,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    doneBtnText: { color: c.chipTextOn, fontSize: 16, fontWeight: '700' },

    // Tirth picker
    tirthOptionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.rowBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 16,
      marginBottom: 10,
    },
    tirthOptionRowOn: { borderColor: c.gold },
    tirthOptionName: { color: c.text, fontSize: 16, fontWeight: '700' },
    tirthOptionNameOn: { color: c.goldBright },
    tirthOptionPlace: { color: c.textMuted, fontSize: 12, marginTop: 3 },
    tirthOptionCheck: { color: c.gold, fontSize: 16, fontWeight: '700' },

    // Prayer-time reminders (Settings)
    prayerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: c.rowBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 16,
      marginBottom: 10,
    },
    prayerRowTime: { color: c.text, fontSize: 17, fontWeight: '700' },
    prayerRowDays: { color: c.textMuted, fontSize: 12, marginTop: 3 },
    prayerRowActions: { flexDirection: 'row', alignItems: 'center', gap: 16 },
    prayerRowRemove: { padding: 4 },
    prayerRowRemoveIcon: { color: c.textMuted, fontSize: 16 },
    addPrayerBtn: {
      borderWidth: 1.5,
      borderColor: c.gold,
      borderStyle: 'dashed',
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 20,
    },
    addPrayerBtnText: { color: c.gold, fontSize: 15, fontWeight: '700' },

    // Time picker modal
    timePickerTitle: {
      color: c.goldBright,
      fontSize: 34,
      fontWeight: '700',
      textAlign: 'center',
      marginBottom: 18,
    },
    timePickerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 18,
      marginBottom: 22,
    },
    timePickerCol: { alignItems: 'center', width: 88 },
    timePickerColLabel: {
      color: c.textMuted,
      fontSize: 12,
      letterSpacing: 1,
      textTransform: 'uppercase',
      marginBottom: 8,
    },
    stepperBtn: {
      width: 56,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.chipBg,
      borderWidth: 1,
      borderColor: c.chipBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperIcon: { color: c.gold, fontSize: 14 },
    timePickerValue: { color: c.text, fontSize: 36, fontWeight: '700', marginVertical: 8 },
    timePickerColon: { color: c.text, fontSize: 30, fontWeight: '700', marginTop: 20 },
    daysRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 22,
    },
    dayChip: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.chipBg,
      borderWidth: 1,
      borderColor: c.chipBorder,
    },
    dayChipOn: { backgroundColor: c.gold, borderColor: c.gold },
    dayChipText: { color: c.textMuted, fontSize: 12, fontWeight: '600' },
    dayChipTextOn: { color: c.chipTextOn },
    timePickerActions: { flexDirection: 'row', gap: 12 },
    cancelBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    cancelBtnText: { color: c.textMuted, fontSize: 16, fontWeight: '600' },
    // Distinct from Settings' standalone `doneBtn` — this one lives in a row
    // next to Cancel, so it needs flex:1 (reusing doneBtn here made the two
    // buttons render at mismatched widths).
    timePickerSaveBtn: {
      flex: 1,
      backgroundColor: c.gold,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    timePickerSaveBtnText: { color: c.chipTextOn, fontSize: 16, fontWeight: '700' },

    // First-launch language dialog (centered, over a blurred backdrop)
    languageBackdrop: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 28 },
    languageCard: {
      width: '100%',
      maxWidth: 340,
      backgroundColor: c.sheetBg,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: c.cardBorder,
      paddingHorizontal: 22,
      paddingTop: 22,
      paddingBottom: 26,
      alignItems: 'center',
    },
    languageTitle: { color: c.goldBright, fontSize: 20, fontWeight: '700', textAlign: 'center' },
    languageSubtitle: {
      color: c.textMuted,
      fontSize: 13,
      marginTop: 6,
      marginBottom: 20,
      textAlign: 'center',
    },
    languageOptions: { width: '100%', gap: 10 },
    languageOptionBtn: {
      width: '100%',
      backgroundColor: c.chipBg,
      borderWidth: 1,
      borderColor: c.chipBorder,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    languageOptionText: { color: c.text, fontSize: 17, fontWeight: '700' },

    // Milestone / anniversary sheet
    // react-native-web makes ScrollView focusable/scrollable via a <div>,
    // which picks up Chrome's default black focus-ring outline — suppress it.
    milestoneScroll: { outlineStyle: 'none' },
    milestoneIconWrap: { alignItems: 'center', marginBottom: 14 },
    milestoneIconBadge: {
      width: 96,
      height: 96,
      borderRadius: 48,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    milestoneTitle: {
      color: c.goldBright,
      fontSize: 20,
      fontWeight: '700',
      textAlign: 'center',
      marginBottom: 10,
    },
    milestoneMessage: {
      color: c.text,
      fontSize: 15,
      lineHeight: 22,
      textAlign: 'left',
      marginBottom: 18,
    },
    milestoneBulletGroup: {
      backgroundColor: c.cardBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 16,
      paddingVertical: 6,
      paddingHorizontal: 12,
      marginBottom: 18,
      gap: 10,
    },
    milestoneBulletRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
      gap: 10,
    },
    milestoneBulletIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.sheetBg,
      borderWidth: 1,
      borderColor: c.cardBorder,
    },
    milestoneBulletText: {
      flex: 1,
      color: c.text,
      fontSize: 14,
      lineHeight: 20,
    },
    milestoneActions: { flexDirection: 'row', gap: 12, marginBottom: 8 },
    milestoneNoBtn: {
      flex: 1,
      borderWidth: 1,
      borderColor: c.cardBorder,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    milestoneNoText: { color: c.textMuted, fontSize: 16, fontWeight: '600' },
    milestoneYesBtn: {
      flex: 1,
      backgroundColor: c.gold,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
    },
    milestoneYesText: { color: c.chipTextOn, fontSize: 16, fontWeight: '700' },

    // Full-screen prayer overlay (real tirth photo backdrop)
    prayerContainer: { flex: 1 },
    prayerScrollContent: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 60,
    },
    // Dims the photo so the light-on-dark mantra text stays readable —
    // fixed (not theme-dependent) since the photo's brightness doesn't
    // change with the light/dark toggle.
    prayerScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(12,9,4,0.55)' },
    prayerCloseBtn: {
      position: 'absolute',
      top: Platform.OS === 'ios' ? 56 : 32,
      right: 20,
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.14)',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 20,
      elevation: 20,
    },
    prayerCloseIcon: { color: '#fff', fontSize: 18 },
    prayerContent: { alignItems: 'center', paddingHorizontal: 28 },
    prayerFacingLine: {
      color: '#7be3a4',
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 28,
    },
    prayerMantraTitle: {
      color: '#ffd76b',
      fontSize: 20,
      fontWeight: '700',
      textAlign: 'center',
      marginBottom: 20,
      letterSpacing: 1,
    },
    prayerMantraBlock: { marginBottom: 28 },
    prayerMantraLine: {
      color: '#fdf3da',
      fontSize: 20,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 14,
    },
    prayerVerseLine: {
      color: '#e6d9c2',
      fontSize: 18,
      fontWeight: '600',
      textAlign: 'center',
      marginBottom: 12,
    },
    prayerPranamLine: { color: '#ffd76b', fontSize: 17, fontWeight: '700', textAlign: 'center' },
  });
}
